[tool.poetry]
name = "pinnwand"
version = "0.1.0"
description = "Straightforward pastebin software."
authors = ["supakeen <cmdr@supakeen.com>"]

[tool.poetry.dependencies]
python = ">=3.6"
tornado = "^6.0"
pygments = "^2.4"
sqlalchemy = "^1.3"
click = "^7.0"

[tool.black]
line-length = 80
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.eggs
  | \.mypy_cache
  | \.tox
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
[build-system]
requires = ["setuptools", "wheel"]

